#ifndef _ERROR_CODE_H_
#define _ERROR_CODE_H_

#define EC_OTSCLIENT_BASE		0
#define EC_SUCCESS				0 // success code
#define EC_OTSCLIENT_MALLOC_FAILED			EC_OTSCLIENT_BASE + 1 // malloc failed
#define EC_OTSCLIENT_NULL_POINTER			EC_OTSCLIENT_BASE + 2
#define EC_OTSCLIENT_INVALID_ARGUMENT		EC_OTSCLIENT_BASE + 3
#define EC_OTSCLIENT_LACK_HASH_KEY			EC_OTSCLIENT_BASE + 4
#define EC_OTSCLIENT_LACK_RANGE_KEY			EC_OTSCLIENT_BASE + 5


#define EC_OTSCLIENT_NO_AUTHORITY			EC_OTSCLIENT_BASE + 6
#define EC_OTSCLIENT_COLUMNS_NULL			EC_OTSCLIENT_BASE + 7
#define EC_OTSCLIENT_BEYOUND_ARRAY_RANGE	EC_OTSCLIENT_BASE + 8
#define EC_OTSCLIENT_QUERY_END				EC_OTSCLIENT_BASE + 9
#define EC_OTSCLIENT_CLIENT_NOT_CREATE				EC_OTSCLIENT_BASE + 10
#define EC_OTSCLIENT_CLIENT_NOT_LOGIN				EC_OTSCLIENT_BASE + 11
#define EC_OTSCLIENT_QUERY_NOT_CREATE				EC_OTSCLIENT_BASE + 12


#endif